#line 2 "align/clustall.c"

#line 4 "align/clustall.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer clustal_create_buffer
#define yy_delete_buffer clustal_delete_buffer
#define yy_flex_debug clustal_flex_debug
#define yy_init_buffer clustal_init_buffer
#define yy_flush_buffer clustal_flush_buffer
#define yy_load_buffer_state clustal_load_buffer_state
#define yy_switch_to_buffer clustal_switch_to_buffer
#define yyin clustalin
#define yyleng clustalleng
#define yylex clustallex
#define yylineno clustallineno
#define yyout clustalout
#define yyrestart clustalrestart
#define yytext clustaltext
#define yywrap clustalwrap
#define yyalloc clustalalloc
#define yyrealloc clustalrealloc
#define yyfree clustalfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#ifdef _LIBC
#include "namespace.h"
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/*	$NetBSD: flexint.h,v 1.1.1.1 2009/10/26 00:26:19 christos Exp $	*/

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE clustalrestart(clustalin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int clustalleng;

extern FILE *clustalin, *clustalout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up clustaltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up clustaltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via clustalrestart()), so that the user can continue scanning by
	 * just pointing clustalin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when clustaltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int clustalleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow clustalwrap()'s to do buffer switches
 * instead of setting up a fresh clustalin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void clustalrestart (FILE *input_file  );
void clustal_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE clustal_create_buffer (FILE *file,int size  );
void clustal_delete_buffer (YY_BUFFER_STATE b  );
void clustal_flush_buffer (YY_BUFFER_STATE b  );
void clustalpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void clustalpop_buffer_state (void );

static void clustalensure_buffer_stack (void );
static void clustal_load_buffer_state (void );
static void clustal_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER clustal_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE clustal_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE clustal_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE clustal_scan_bytes (yyconst char *bytes,int len  );

void *clustalalloc (yy_size_t  );
void *clustalrealloc (void *,yy_size_t  );
void clustalfree (void *  );

#define yy_new_buffer clustal_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        clustalensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            clustal_create_buffer(clustalin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        clustalensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            clustal_create_buffer(clustalin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define clustalwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *clustalin = (FILE *) 0, *clustalout = (FILE *) 0;

typedef int yy_state_type;

extern int clustallineno;

int clustallineno = 1;

extern char *clustaltext;
#define yytext_ptr clustaltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up clustaltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	clustalleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 24
#define YY_END_OF_BUFFER 25
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[581] =
    {   0,
       25,   23,   24,   22,   24,    3,   23,   24,    1,   22,
       24,16386,16392,    3,   23,   24,   23,   24,   23,   24,
        5,   24,    6,   24,   18,   24,   13,   18,   24,   17,
       24,   11,   18,   24,   12,   18,   24,   10,   18,   24,
       10,   18,   24,   10,   11,   18,   24,   10,   12,   18,
       24,   21,   24,   19,   21,   24,   20,   24,    3,    1,
    16386, 8200,16386,16392, 8200, 8200,    1,16386,16392,    3,
        5,    7,   13,   14,   15,   16,   15,   16,   11,   12,
       10,   10,   10,   10,   11,   10,   12,   19,16386, 8200,
     8200, 8200,    5,    7,   15,   16,   15,   16,   11,   10,

       10,   10,   11,   10,   12,   19, 8200, 8200, 8200,    5,
        7,   15,   16,   15,   16,   11,   10,   10,   10,   11,
       10,   12,   19, 8200, 8200, 8200,    5,    7,   15,   16,
       15,   16,   11,   10,   10,   10,   11,   10,   12,   19,
     8200, 8200, 8200,    5,    7,   15,   16,   15,   16,   11,
       10,   10,    9,   10,   11,   10,   12,   19, 8200, 8200,
     8200,    4,    5,    7,   15,   16,   15,   16,   11,   10,
       10,   10,   11,   10,   12,   19, 8200, 8194, 8200,    5,
        7,   15,   16,   15,   16,   11,   10,   10,   10,   11,
       10,   12,   19, 8194, 8200,    5,    7,   15,   16,   15,

       16,   11,   10,   10,   10,   11,   10,   12,   19, 8200,
        5,    7,   15,   16,   15,   16,   11,   10,   10,   10,
       11,   10,   12,   19, 8200,    5,    7,   15,   16,   15,
       16,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,

        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,

       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,

        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,   10,   10,   10,   12, 8200,    5,    7,   15,   10,
       10,   10,   12, 8200,    5,    7,   15,   10,   10,   10,
       12, 8200,    5,    7,   15,   10,   10,   10,   12, 8200,
        5,    7,   15,   10,   10,   10,   12, 8200,    5,    7,
       15,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_accept[509] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    6,    9,   14,   17,   19,   21,   23,   25,   27,
       30,   32,   35,   38,   41,   44,   48,   52,   54,   57,
       59,   60,   62,   63,   65,   66,   67,   70,   71,   71,
       71,   72,   73,   74,   75,   76,   77,   79,   80,   81,
       82,   83,   84,   86,   88,   89,   90,   90,   90,   91,
       92,   93,   93,   93,   94,   95,   96,   97,   99,  100,
      101,  102,  104,  106,  107,  107,  107,  108,  109,  110,
      110,  110,  111,  112,  113,  114,  116,  117,  118,  119,
      121,  123,  124,  124,  124,  125,  126,  127,  127,  127,

      128,  129,  130,  131,  133,  134,  135,  136,  138,  140,
      141,  141,  141,  142,  143,  144,  144,  144,  145,  146,
      147,  148,  150,  151,  152,  153,  153,  154,  156,  158,
      159,  159,  159,  160,  161,  162,  163,  164,  165,  166,
      167,  169,  170,  171,  172,  174,  176,  177,  177,  177,
      178,  180,  181,  182,  183,  184,  186,  187,  188,  189,
      191,  193,  194,  195,  196,  197,  198,  199,  200,  202,
      203,  204,  205,  207,  209,  210,  211,  212,  213,  214,
      215,  217,  218,  219,  220,  222,  224,  225,  226,  227,
      228,  229,  230,  232,  233,  234,  236,  237,  238,  239,

      240,  241,  242,  244,  245,  246,  247,  248,  249,  250,
      252,  253,  254,  255,  256,  257,  258,  260,  261,  262,
      263,  264,  265,  266,  268,  269,  270,  271,  272,  273,
      274,  276,  277,  278,  279,  280,  281,  282,  284,  285,
      286,  287,  288,  289,  290,  292,  293,  294,  295,  296,
      297,  298,  300,  301,  302,  303,  304,  305,  306,  308,
      309,  310,  311,  312,  313,  314,  316,  317,  318,  319,
      320,  321,  322,  324,  325,  326,  327,  328,  329,  330,
      332,  333,  334,  335,  336,  337,  338,  340,  341,  342,
      343,  344,  345,  346,  348,  349,  350,  351,  352,  353,

      354,  356,  357,  358,  359,  360,  361,  362,  364,  365,
      366,  367,  368,  369,  370,  372,  373,  374,  375,  376,
      377,  378,  380,  381,  382,  383,  384,  385,  386,  388,
      389,  390,  391,  392,  393,  394,  396,  397,  398,  399,
      400,  401,  402,  404,  405,  406,  407,  408,  409,  410,
      412,  413,  414,  415,  416,  417,  418,  420,  421,  422,
      423,  424,  425,  426,  428,  429,  430,  431,  432,  433,
      434,  436,  437,  438,  439,  440,  441,  442,  444,  445,
      446,  447,  448,  449,  450,  452,  453,  454,  455,  456,
      457,  458,  460,  461,  462,  463,  464,  465,  466,  468,

      469,  470,  471,  472,  473,  474,  476,  477,  478,  479,
      480,  481,  482,  484,  485,  486,  487,  488,  489,  490,
      492,  493,  494,  495,  496,  497,  498,  500,  501,  502,
      503,  504,  505,  506,  508,  509,  510,  511,  512,  513,
      514,  516,  517,  518,  519,  520,  521,  522,  524,  525,
      526,  527,  528,  529,  530,  532,  533,  534,  535,  536,
      537,  538,  540,  541,  542,  543,  544,  545,  546,  548,
      549,  550,  551,  552,  552,  553,  553,  554,  554,  555,
      555,  556,  557,  558,  559,  560,  561,  562,  563,  564,
      565,  566,  567,  568,  569,  570,  571,  572,  573,  574,

      575,  576,  577,  578,  579,  580,  581,  581
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,    1,    1,
        1,    1,   11,    1,   12,   13,   14,   13,   13,   13,
       15,   13,   13,   13,   13,   16,   17,   13,   13,   13,
       13,   13,   18,   19,   20,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   21,    1,   22,   13,   23,   13,

       13,   13,   13,   13,   13,   13,   13,   24,   13,   13,
       13,   13,   13,   13,   25,   26,   27,   13,   13,   13,
       13,   13,    1,    1,    1,   28,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[29] =
    {   0,
        1,    2,    3,    2,    1,    4,    4,    4,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[859] =
    {   0,
      481,    0,  479,  477,   23,   51,   78,   87,  477, 1937,
     1937,    3,   80,    6,   76,  451,    0,    0, 1937,    9,
      102,    0,  464,    0,    0,  112,  462, 1937,  132, 1937,
       17,   82,    0,   84,   85,  444,  112,  116,  427,  418,
        0,    0,  121, 1937,    0,  141,  150,    0,  434,    0,
      424,  420,  160,  427,  180,  125,  113,  410,    0,  412,
      402,  409,  400,    0,    0,    0,  189,  198,    0,    0,
      402,  208,  411,  228,  379,  370,    0,  377,  368,  371,
      362,    0,    0,    0,  237,  246,    0,    0,    0,  256,
      377,  276,  366,  356,    0,  360,  351,  363,  350,    0,

        0,    0,  285,  294,    0,    0,  128,  304,  342,  324,
      330,  321,    0,  333,  320,  324,  314,    0,    0,    0,
      333,  342,    0,    0,  160,  333, 1937,  352,  324,  372,
      319,  307,    0,  311,  300, 1937,    0,    0,    0,  381,
      390,    0,    0,  164,  400,  294,  420,  285,  275,    0,
        0,    0,    0,    0,  429,  438,    0,    0,  169,  448,
      288,  468, 1937,    0,    0,    0,    0,  477,  486,    0,
        0,  172,  496,  285,  516,    0,    0,    0,    0,  525,
      534, 1937,    0,  175,    0,  283, 1937,    0,    0,    0,
        0, 1937,    0,    0,  208,  281,    0,    0,    0,    0,

        0,  212,  279,    0,    0,    0,    0,    0,  217,  276,
        0,    0,    0,    0,    0,  220,  274,    0,    0,    0,
        0,    0,  223,  272,    0,    0,    0,    0,    0,  256,
      270,    0,    0,    0,    0,    0,  260,  267,    0,    0,
        0,    0,    0,  265,  246,    0,    0,    0,    0,    0,
      268,  244,    0,    0,    0,    0,    0,  271,  242,    0,
        0,    0,    0,    0,  304,  240,    0,    0,    0,    0,
        0,  308,  237,    0,    0,    0,    0,    0,  313,  235,
        0,    0,    0,    0,    0,  316,  233,    0,    0,    0,
        0,    0,  319,  231,    0,    0,    0,    0,    0,  352,

      228,    0,    0,    0,    0,    0,  356,  226,    0,    0,
        0,    0,    0,  361,  224,    0,    0,    0,    0,    0,
      364,  222,    0,    0,    0,    0,    0,  367,  219,    0,
        0,    0,    0,    0,  400,  198,    0,    0,    0,    0,
        0,  404,  196,    0,    0,    0,    0,    0,  409,  194,
        0,    0,    0,    0,    0,  412,  192,    0,    0,    0,
        0,    0,  415,  189,    0,    0,    0,    0,    0,  448,
      187,    0,    0,    0,    0,    0,  452,  185,    0,    0,
        0,    0,    0,  457,  183,    0,    0,    0,    0,    0,
      460,  180,    0,    0,    0,    0,    0,  463,  178,    0,

        0,    0,    0,    0,  496,  176,    0,    0,    0,    0,
        0,  500,  174,    0,    0,    0,    0,    0,  505,  171,
        0,    0,    0,    0,    0,  508,  150,    0,    0,    0,
        0,    0,  511,  148,    0,    0,    0,    0,    0,  543,
      146,    0,    0,    0,    0,    0,  546,  144,    0,    0,
        0,    0,    0,  549,  141,    0,    0,    0,    0,    0,
      552,  137,    0,    0,    0,    0, 1937,  555,  135, 1937,
        0, 1937, 1937,  558,    0,  561,    0,  564,    0,  138,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0, 1937, 1937,  568,  572,  576,
      580,  584,  588,  592,  123,  596,  600,  604,  608,  612,
      616,  112,  620,  624,  628,  632,  636,  640,  110,  644,
      648,  652,  656,  660,  664,  107,  668,  672,  676,  680,
      684,  688,  692,   98,  696,  700,  704,  708,  712,  716,
      720,   95,  724,  728,  732,  736,  740,  744,  748,  752,
       18,  756,  760,  764,  768,  772,  776,  780,   13,  784,
      788,  792,  796,  800,  804,  808,   12,  812,  816,  820,
      824,  828,  832,  836,  840,  844,  848,  852,  856,  860,
      864,  868,  872,  876,  880,  884,  888,  892,  896,  900,

      904,  908,  912,  916,  920,  924,  928,  932,  936,  940,
      944,  948,  952,  956,  960,  964,  968,  972,  976,  980,
      984,  988,  992,  996, 1000, 1004, 1008, 1012, 1016, 1020,
     1024, 1028, 1032, 1036, 1040, 1044, 1048, 1052, 1056, 1060,
     1064, 1068, 1072, 1076, 1080, 1084, 1088, 1092, 1096, 1100,
     1104, 1108, 1112, 1116, 1120, 1124, 1128, 1132, 1136, 1140,
     1144, 1148, 1152, 1156, 1160, 1164, 1168, 1172, 1176, 1180,
     1184, 1188, 1192, 1196, 1200, 1204, 1208, 1212, 1216, 1220,
     1224, 1228, 1232, 1236, 1240, 1244, 1248, 1252, 1256, 1260,
     1264, 1268, 1272, 1276, 1280, 1284, 1288, 1292, 1296, 1300,

     1304, 1308, 1312, 1316, 1320, 1324, 1328, 1332, 1336, 1340,
     1344, 1348, 1352, 1356, 1360, 1364, 1368, 1372, 1376, 1380,
     1384, 1388, 1392, 1396, 1400, 1404, 1408, 1412, 1416, 1420,
     1424, 1428, 1432, 1436, 1440, 1444, 1448, 1452, 1456, 1460,
     1464, 1468, 1472, 1476, 1480, 1484, 1488, 1492, 1496, 1500,
     1504, 1508, 1512, 1516, 1520, 1524, 1528, 1532, 1536, 1540,
     1544, 1548, 1552, 1556, 1560, 1564, 1568, 1572, 1576, 1580,
     1584, 1588, 1592, 1596, 1600, 1604, 1608, 1612, 1616, 1620,
     1624, 1628, 1632, 1636, 1640, 1644, 1648, 1652, 1656, 1660,
     1664, 1668, 1672, 1676, 1680, 1684, 1688, 1692, 1696, 1700,

     1704, 1708, 1712, 1716, 1720, 1724, 1728, 1732, 1736, 1740,
     1744, 1748, 1752, 1756, 1760, 1764, 1768, 1772, 1776, 1780,
     1784, 1788, 1792, 1796, 1800, 1804, 1808, 1812, 1816, 1820,
     1824, 1828, 1832, 1836, 1840, 1844, 1848, 1852, 1856, 1860,
     1864, 1868, 1872, 1876, 1880, 1884, 1888, 1892, 1896, 1900,
     1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932
    } ;

static yyconst flex_int16_t yy_def[859] =
    {   0,
      508,  508,  509,  509,  507,  507,  510,  510,  507,  507,
      507,  507,  511,  507,  507,  507,  512,  513,  507,  507,
      514,  515,  507,  516,  516,  517,  516,  507,  507,  507,
      507,  507,  518,  511,  518,  518,  511,  507,  507,  507,
      519,  520,  507,  507,  521,  507,  521,  522,  507,  523,
      523,  523,  524,  523,  507,  507,  507,  507,  525,  525,
      525,  507,  507,  526,  527,  528,  507,  528,  529,  530,
      530,  531,  530,  507,  507,  507,  532,  532,  532,  507,
      507,  533,  534,  535,  507,  535,  536,  537,  538,  539,
      537,  507,  507,  507,  540,  540,  540,  507,  507,  541,

      542,  543,  507,  543,  544,  545,  546,  547,  545,  507,
      507,  507,  548,  548,  548,  507,  507,  549,  550,  551,
      507,  551,  552,  553,  554,  555,  507,  556,  553,  507,
      507,  507,  557,  557,  557,  507,  558,  559,  560,  507,
      560,  561,  562,  563,  564,  562,  507,  507,  507,  565,
      565,  566,  567,  568,  507,  568,  569,  570,  571,  572,
      570,  507,  507,  573,  574,  575,  576,  507,  576,  577,
      578,  579,  580,  578,  507,  581,  582,  583,  584,  507,
      584,  507,  585,  586,  585,  585,  507,  587,  588,  589,
      590,  507,  590,  591,  592,  591,  593,  594,  595,  596,

      597,  598,  597,  599,  600,  601,  602,  603,  604,  603,
      605,  606,  607,  608,  609,  610,  609,  611,  612,  613,
      614,  615,  616,  615,  617,  618,  619,  620,  621,  622,
      621,  623,  624,  625,  626,  627,  628,  627,  629,  630,
      631,  632,  633,  634,  633,  635,  636,  637,  638,  639,
      640,  639,  641,  642,  643,  644,  645,  646,  645,  647,
      648,  649,  650,  651,  652,  651,  653,  654,  655,  656,
      657,  658,  657,  659,  660,  661,  662,  663,  664,  663,
      665,  666,  667,  668,  669,  670,  669,  671,  672,  673,
      674,  675,  676,  675,  677,  678,  679,  680,  681,  682,

      681,  683,  684,  685,  686,  687,  688,  687,  689,  690,
      691,  692,  693,  694,  693,  695,  696,  697,  698,  699,
      700,  699,  701,  702,  703,  704,  705,  706,  705,  707,
      708,  709,  710,  711,  712,  711,  713,  714,  715,  716,
      717,  718,  717,  719,  720,  721,  722,  723,  724,  723,
      725,  726,  727,  728,  729,  730,  729,  731,  732,  733,
      734,  735,  736,  735,  737,  738,  739,  740,  741,  742,
      741,  743,  744,  745,  746,  747,  748,  747,  749,  750,
      751,  752,  753,  754,  753,  755,  756,  757,  758,  759,
      760,  759,  761,  762,  763,  764,  765,  766,  765,  767,

      768,  769,  770,  771,  772,  771,  773,  774,  775,  776,
      777,  778,  777,  779,  780,  781,  782,  783,  784,  783,
      785,  786,  787,  788,  789,  790,  789,  791,  792,  793,
      794,  795,  796,  795,  797,  798,  799,  800,  801,  802,
      801,  803,  804,  805,  806,  807,  808,  807,  809,  810,
      811,  812,  813,  814,  813,  815,  816,  817,  818,  819,
      820,  819,  821,  822,  823,  824,  507,  825,  507,  507,
      826,  507,  507,  827,  828,  829,  830,  831,  832,  833,
      834,  835,  836,  837,  838,  839,  840,  841,  842,  843,
      844,  845,  846,  847,  848,  849,  850,  851,  852,  853,

      854,  855,  856,  857,  858,  507,    0,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507
    } ;

static yyconst flex_int16_t yy_nxt[1966] =
    {   0,
      507,   12,   13,   14,   31,   32,   31,   31,   37,   38,
       43,   44,   43,   15,   51,  182,  170,   52,   31,   32,
       31,  157,   16,   19,   20,   21,   20,   19,   22,   22,
       22,   23,   19,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   19,   22,   22,   22,   22,   22,   22,
       22,   24,   20,   21,   20,   25,   26,   26,   26,   27,
       24,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   24,   26,   26,   26,   26,   26,   26,   26,   29,
       30,   29,   34,   29,   56,   29,   34,   29,   29,   30,
       29,   39,   29,   35,   29,   57,   29,   35,  142,   40,

       60,  123,   36,   46,   58,   46,   36,   47,   61,   47,
      105,   47,   50,   87,   34,   69,   50,   31,   37,   38,
       50,   50,   43,   44,   43,   35,   48,   56,   75,  126,
      127,  126,   50,   55,   36,   55,   76,   55,   57,   55,
      127,   55,   67,   49,   67,  469,   67,   58,   67,  462,
       67,   67,  455,   67,  448,   68,  441,   68,  434,   68,
       70,  126,  127,  126,   70,  126,  127,  126,   70,   70,
      126,  127,  126,  126,  127,  126,  126,  127,  126,  427,
       70,   74,  420,   74,  413,   74,  406,   74,  399,   74,
       85,  392,   85,  385,   85,  378,   85,  371,   85,   85,

      364,   85,  357,   86,  350,   86,  343,   86,   88,  126,
      127,  126,   88,  126,  127,  126,   88,   88,  126,  127,
      126,  126,  127,  126,  126,  127,  126,  336,   88,   92,
      329,   92,  322,   92,  315,   92,  308,   92,  103,  301,
      103,  294,  103,  287,  103,  280,  103,  103,  273,  103,
      266,  104,  259,  104,  252,  104,  106,  126,  127,  126,
      106,  126,  127,  126,  106,  106,  126,  127,  126,  126,
      127,  126,  126,  127,  126,  245,  106,  110,  238,  110,
      231,  110,  224,  110,  217,  110,  121,  210,  121,  203,
      121,  196,  121,  186,  121,  121,  174,  121,  163,  122,

      163,  122,  161,  122,  124,  126,  127,  126,  124,  126,
      127,  126,  124,  124,  126,  127,  126,  126,  127,  126,
      126,  127,  126,  151,  124,  130,  151,  130,  149,  130,
      148,  130,  146,  130,  140,  127,  140,  136,  140,  136,
      140,  135,  140,  140,  134,  140,  132,  141,  131,  141,
      129,  141,  143,  126,  127,  126,  143,  126,  127,  126,
      143,  143,  126,  127,  126,  126,  127,  126,  126,  127,
      126,  117,  143,  147,  116,  147,  115,  147,  114,  147,
      112,  147,  155,  111,  155,  109,  155,   99,  155,   98,
      155,  155,   97,  155,   96,  156,   94,  156,   93,  156,

      158,  126,  127,  126,  158,  126,  127,  126,  158,  158,
      126,  127,  126,  126,  127,  126,  126,  127,  126,   91,
      158,  162,   89,  162,   81,  162,   80,  162,   79,  162,
      168,   78,  168,   76,  168,   73,  168,   71,  168,  168,
       71,  168,   49,  169,   63,  169,   62,  169,  171,  126,
      127,  126,  171,  126,  127,  126,  171,  171,  126,  127,
      126,  126,  127,  126,  126,  127,  126,   61,  171,  175,
       54,  175,   49,  175,   40,  175,  507,  175,  180,   18,
      180,   18,  180,   11,  180,  507,  180,  180,  507,  180,
      507,  181,  507,  181,  507,  181,  183,  126,  127,  126,

      183,  126,  127,  126,  183,  183,  126,  127,  126,  126,
      127,  126,  126,  127,  126,  507,  183,  187,  507,  187,
      507,  187,  507,  187,  507,  187,  192,  507,  192,  507,
      192,  507,  192,  507,  192,  192,  507,  192,  507,  193,
      507,  193,  507,  193,  126,  127,  126,  126,  127,  126,
      126,  127,  126,  126,  127,  126,  126,  127,  126,  126,
      127,  126,  126,  127,  126,  126,  127,  126,   10,   10,
       10,   10,   17,   17,   17,   17,   28,   28,   28,   28,
       33,  507,   33,   33,   41,   41,  507,   41,   42,  507,
      507,   42,   45,   45,  507,   45,   50,  507,  507,   50,

       53,  507,  507,   53,   59,  507,  507,   59,   64,   64,
      507,   64,   65,  507,  507,   65,   66,  507,  507,   66,
       70,  507,  507,   70,   72,  507,  507,   72,   77,  507,
      507,   77,   82,   82,  507,   82,   83,  507,  507,   83,
       84,  507,  507,   84,   88,  507,  507,   88,   90,  507,
      507,   90,   95,  507,  507,   95,  100,  100,  507,  100,
      101,  507,  507,  101,  102,  507,  507,  102,  106,  507,
      507,  106,  107,  507,  507,  107,  108,  507,  507,  108,
      113,  507,  507,  113,  118,  118,  507,  118,  119,  507,
      507,  119,  120,  507,  507,  120,  124,  507,  507,  124,

      125,  125,  125,  125,  128,  507,  507,  128,  133,  507,
      507,  133,  137,  137,  507,  137,  138,  507,  507,  138,
      139,  507,  507,  139,  143,  507,  507,  143,  144,  144,
      144,  144,  126,  126,  126,  126,  145,  507,  507,  145,
      150,  507,  507,  150,  152,  152,  507,  152,  153,  507,
      507,  153,  154,  507,  507,  154,  158,  507,  507,  158,
      159,  159,  159,  159,  160,  507,  507,  160,  164,  507,
      507,  164,  165,  165,  507,  165,  166,  507,  507,  166,
      167,  507,  507,  167,  171,  507,  507,  171,  172,  172,
      172,  172,  173,  507,  507,  173,  176,  507,  507,  176,

      177,  177,  507,  177,  178,  507,  507,  178,  179,  507,
      507,  179,  183,  507,  507,  183,  184,  184,  184,  184,
      185,  507,  507,  185,  188,  507,  507,  188,  189,  189,
      507,  189,  190,  507,  507,  190,  191,  507,  507,  191,
      194,  507,  507,  194,  195,  195,  195,  195,  197,  507,
      507,  197,  198,  198,  507,  198,  199,  507,  507,  199,
      200,  507,  507,  200,  201,  507,  507,  201,  202,  202,
      202,  202,  204,  507,  507,  204,  205,  205,  507,  205,
      206,  507,  507,  206,  207,  507,  507,  207,  208,  507,
      507,  208,  209,  209,  209,  209,  211,  507,  507,  211,

      212,  212,  507,  212,  213,  507,  507,  213,  214,  507,
      507,  214,  215,  507,  507,  215,  216,  216,  216,  216,
      218,  507,  507,  218,  219,  219,  507,  219,  220,  507,
      507,  220,  221,  507,  507,  221,  222,  507,  507,  222,
      223,  223,  223,  223,  225,  507,  507,  225,  226,  226,
      507,  226,  227,  507,  507,  227,  228,  507,  507,  228,
      229,  507,  507,  229,  230,  230,  230,  230,  232,  507,
      507,  232,  233,  233,  507,  233,  234,  507,  507,  234,
      235,  507,  507,  235,  236,  507,  507,  236,  237,  237,
      237,  237,  239,  507,  507,  239,  240,  240,  507,  240,

      241,  507,  507,  241,  242,  507,  507,  242,  243,  507,
      507,  243,  244,  244,  244,  244,  246,  507,  507,  246,
      247,  247,  507,  247,  248,  507,  507,  248,  249,  507,
      507,  249,  250,  507,  507,  250,  251,  251,  251,  251,
      253,  507,  507,  253,  254,  254,  507,  254,  255,  507,
      507,  255,  256,  507,  507,  256,  257,  507,  507,  257,
      258,  258,  258,  258,  260,  507,  507,  260,  261,  261,
      507,  261,  262,  507,  507,  262,  263,  507,  507,  263,
      264,  507,  507,  264,  265,  265,  265,  265,  267,  507,
      507,  267,  268,  268,  507,  268,  269,  507,  507,  269,

      270,  507,  507,  270,  271,  507,  507,  271,  272,  272,
      272,  272,  274,  507,  507,  274,  275,  275,  507,  275,
      276,  507,  507,  276,  277,  507,  507,  277,  278,  507,
      507,  278,  279,  279,  279,  279,  281,  507,  507,  281,
      282,  282,  507,  282,  283,  507,  507,  283,  284,  507,
      507,  284,  285,  507,  507,  285,  286,  286,  286,  286,
      288,  507,  507,  288,  289,  289,  507,  289,  290,  507,
      507,  290,  291,  507,  507,  291,  292,  507,  507,  292,
      293,  293,  293,  293,  295,  507,  507,  295,  296,  296,
      507,  296,  297,  507,  507,  297,  298,  507,  507,  298,

      299,  507,  507,  299,  300,  300,  300,  300,  302,  507,
      507,  302,  303,  303,  507,  303,  304,  507,  507,  304,
      305,  507,  507,  305,  306,  507,  507,  306,  307,  307,
      307,  307,  309,  507,  507,  309,  310,  310,  507,  310,
      311,  507,  507,  311,  312,  507,  507,  312,  313,  507,
      507,  313,  314,  314,  314,  314,  316,  507,  507,  316,
      317,  317,  507,  317,  318,  507,  507,  318,  319,  507,
      507,  319,  320,  507,  507,  320,  321,  321,  321,  321,
      323,  507,  507,  323,  324,  324,  507,  324,  325,  507,
      507,  325,  326,  507,  507,  326,  327,  507,  507,  327,

      328,  328,  328,  328,  330,  507,  507,  330,  331,  331,
      507,  331,  332,  507,  507,  332,  333,  507,  507,  333,
      334,  507,  507,  334,  335,  335,  335,  335,  337,  507,
      507,  337,  338,  338,  507,  338,  339,  507,  507,  339,
      340,  507,  507,  340,  341,  507,  507,  341,  342,  342,
      342,  342,  344,  507,  507,  344,  345,  345,  507,  345,
      346,  507,  507,  346,  347,  507,  507,  347,  348,  507,
      507,  348,  349,  349,  349,  349,  351,  507,  507,  351,
      352,  352,  507,  352,  353,  507,  507,  353,  354,  507,
      507,  354,  355,  507,  507,  355,  356,  356,  356,  356,

      358,  507,  507,  358,  359,  359,  507,  359,  360,  507,
      507,  360,  361,  507,  507,  361,  362,  507,  507,  362,
      363,  363,  363,  363,  365,  507,  507,  365,  366,  366,
      507,  366,  367,  507,  507,  367,  368,  507,  507,  368,
      369,  507,  507,  369,  370,  370,  370,  370,  372,  507,
      507,  372,  373,  373,  507,  373,  374,  507,  507,  374,
      375,  507,  507,  375,  376,  507,  507,  376,  377,  377,
      377,  377,  379,  507,  507,  379,  380,  380,  507,  380,
      381,  507,  507,  381,  382,  507,  507,  382,  383,  507,
      507,  383,  384,  384,  384,  384,  386,  507,  507,  386,

      387,  387,  507,  387,  388,  507,  507,  388,  389,  507,
      507,  389,  390,  507,  507,  390,  391,  391,  391,  391,
      393,  507,  507,  393,  394,  394,  507,  394,  395,  507,
      507,  395,  396,  507,  507,  396,  397,  507,  507,  397,
      398,  398,  398,  398,  400,  507,  507,  400,  401,  401,
      507,  401,  402,  507,  507,  402,  403,  507,  507,  403,
      404,  507,  507,  404,  405,  405,  405,  405,  407,  507,
      507,  407,  408,  408,  507,  408,  409,  507,  507,  409,
      410,  507,  507,  410,  411,  507,  507,  411,  412,  412,
      412,  412,  414,  507,  507,  414,  415,  415,  507,  415,

      416,  507,  507,  416,  417,  507,  507,  417,  418,  507,
      507,  418,  419,  419,  419,  419,  421,  507,  507,  421,
      422,  422,  507,  422,  423,  507,  507,  423,  424,  507,
      507,  424,  425,  507,  507,  425,  426,  426,  426,  426,
      428,  507,  507,  428,  429,  429,  507,  429,  430,  507,
      507,  430,  431,  507,  507,  431,  432,  507,  507,  432,
      433,  433,  433,  433,  435,  507,  507,  435,  436,  436,
      507,  436,  437,  507,  507,  437,  438,  507,  507,  438,
      439,  507,  507,  439,  440,  440,  440,  440,  442,  507,
      507,  442,  443,  443,  507,  443,  444,  507,  507,  444,

      445,  507,  507,  445,  446,  507,  507,  446,  447,  447,
      447,  447,  449,  507,  507,  449,  450,  450,  507,  450,
      451,  507,  507,  451,  452,  507,  507,  452,  453,  507,
      507,  453,  454,  454,  454,  454,  456,  507,  507,  456,
      457,  457,  507,  457,  458,  507,  507,  458,  459,  507,
      507,  459,  460,  507,  507,  460,  461,  461,  461,  461,
      463,  507,  507,  463,  464,  464,  507,  464,  465,  507,
      507,  465,  466,  507,  507,  466,  467,  507,  507,  467,
      468,  468,  468,  468,  470,  507,  507,  470,  471,  471,
      507,  471,  472,  507,  507,  472,  473,  507,  507,  473,

      474,  474,  474,  474,  475,  475,  507,  475,  476,  476,
      476,  476,  477,  477,  507,  477,  478,  478,  478,  478,
      479,  479,  507,  479,  480,  480,  480,  480,  481,  481,
      507,  481,  126,  126,  126,  126,  482,  482,  507,  482,
      483,  483,  507,  483,  484,  484,  507,  484,  485,  485,
      507,  485,  486,  486,  507,  486,  487,  487,  507,  487,
      488,  488,  507,  488,  489,  489,  507,  489,  490,  490,
      507,  490,  491,  491,  507,  491,  492,  492,  507,  492,
      493,  493,  507,  493,  494,  494,  507,  494,  495,  495,
      507,  495,  496,  496,  507,  496,  497,  497,  507,  497,

      498,  498,  507,  498,  499,  499,  507,  499,  500,  500,
      507,  500,  501,  501,  507,  501,  502,  502,  507,  502,
      503,  503,  507,  503,  504,  504,  507,  504,  505,  505,
      507,  505,  506,  506,  507,  506,    9,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507
    } ;

static yyconst flex_int16_t yy_chk[1966] =
    {   0,
        0,    2,    2,    2,   12,   12,   12,   14,   14,   14,
       20,   20,   20,    2,   25,  577,  569,   25,   31,   31,
       31,  561,    2,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    7,
        7,    7,   13,    7,   32,    7,   34,    7,    8,    8,
        8,   15,    8,   13,    8,   32,    8,   34,  552,   15,

       35,  544,   13,   21,   32,   21,   34,   21,   35,   21,
      536,   21,   26,  529,   37,  522,   26,   38,   38,   38,
       26,   26,   43,   43,   43,   37,  515,   56,   57,  107,
      107,  107,   26,   29,   37,   29,   57,   29,   56,   29,
      480,   29,   46,  469,   46,  462,   46,   56,   46,  455,
       46,   47,  448,   47,  441,   47,  434,   47,  427,   47,
       53,  125,  125,  125,   53,  144,  144,  144,   53,   53,
      159,  159,  159,  172,  172,  172,  184,  184,  184,  420,
       53,   55,  413,   55,  406,   55,  399,   55,  392,   55,
       67,  385,   67,  378,   67,  371,   67,  364,   67,   68,

      357,   68,  350,   68,  343,   68,  336,   68,   72,  195,
      195,  195,   72,  202,  202,  202,   72,   72,  209,  209,
      209,  216,  216,  216,  223,  223,  223,  329,   72,   74,
      322,   74,  315,   74,  308,   74,  301,   74,   85,  294,
       85,  287,   85,  280,   85,  273,   85,   86,  266,   86,
      259,   86,  252,   86,  245,   86,   90,  230,  230,  230,
       90,  237,  237,  237,   90,   90,  244,  244,  244,  251,
      251,  251,  258,  258,  258,  238,   90,   92,  231,   92,
      224,   92,  217,   92,  210,   92,  103,  203,  103,  196,
      103,  186,  103,  174,  103,  104,  161,  104,  149,  104,

      148,  104,  146,  104,  108,  265,  265,  265,  108,  272,
      272,  272,  108,  108,  279,  279,  279,  286,  286,  286,
      293,  293,  293,  135,  108,  110,  134,  110,  132,  110,
      131,  110,  129,  110,  121,  126,  121,  117,  121,  116,
      121,  115,  121,  122,  114,  122,  112,  122,  111,  122,
      109,  122,  128,  300,  300,  300,  128,  307,  307,  307,
      128,  128,  314,  314,  314,  321,  321,  321,  328,  328,
      328,   99,  128,  130,   98,  130,   97,  130,   96,  130,
       94,  130,  140,   93,  140,   91,  140,   81,  140,   80,
      140,  141,   79,  141,   78,  141,   76,  141,   75,  141,

      145,  335,  335,  335,  145,  342,  342,  342,  145,  145,
      349,  349,  349,  356,  356,  356,  363,  363,  363,   73,
      145,  147,   71,  147,   63,  147,   62,  147,   61,  147,
      155,   60,  155,   58,  155,   54,  155,   52,  155,  156,
       51,  156,   49,  156,   40,  156,   39,  156,  160,  370,
      370,  370,  160,  377,  377,  377,  160,  160,  384,  384,
      384,  391,  391,  391,  398,  398,  398,   36,  160,  162,
       27,  162,   23,  162,   16,  162,    9,  162,  168,    4,
      168,    3,  168,    1,  168,    0,  168,  169,    0,  169,
        0,  169,    0,  169,    0,  169,  173,  405,  405,  405,

      173,  412,  412,  412,  173,  173,  419,  419,  419,  426,
      426,  426,  433,  433,  433,    0,  173,  175,    0,  175,
        0,  175,    0,  175,    0,  175,  180,    0,  180,    0,
      180,    0,  180,    0,  180,  181,    0,  181,    0,  181,
        0,  181,    0,  181,  440,  440,  440,  447,  447,  447,
      454,  454,  454,  461,  461,  461,  468,  468,  468,  474,
      474,  474,  476,  476,  476,  478,  478,  478,  508,  508,
      508,  508,  509,  509,  509,  509,  510,  510,  510,  510,
      511,    0,  511,  511,  512,  512,    0,  512,  513,    0,
        0,  513,  514,  514,    0,  514,  516,    0,    0,  516,

      517,    0,    0,  517,  518,    0,    0,  518,  519,  519,
        0,  519,  520,    0,    0,  520,  521,    0,    0,  521,
      523,    0,    0,  523,  524,    0,    0,  524,  525,    0,
        0,  525,  526,  526,    0,  526,  527,    0,    0,  527,
      528,    0,    0,  528,  530,    0,    0,  530,  531,    0,
        0,  531,  532,    0,    0,  532,  533,  533,    0,  533,
      534,    0,    0,  534,  535,    0,    0,  535,  537,    0,
        0,  537,  538,    0,    0,  538,  539,    0,    0,  539,
      540,    0,    0,  540,  541,  541,    0,  541,  542,    0,
        0,  542,  543,    0,    0,  543,  545,    0,    0,  545,

      546,  546,  546,  546,  547,    0,    0,  547,  548,    0,
        0,  548,  549,  549,    0,  549,  550,    0,    0,  550,
      551,    0,    0,  551,  553,    0,    0,  553,  554,  554,
      554,  554,  555,  555,  555,  555,  556,    0,    0,  556,
      557,    0,    0,  557,  558,  558,    0,  558,  559,    0,
        0,  559,  560,    0,    0,  560,  562,    0,    0,  562,
      563,  563,  563,  563,  564,    0,    0,  564,  565,    0,
        0,  565,  566,  566,    0,  566,  567,    0,    0,  567,
      568,    0,    0,  568,  570,    0,    0,  570,  571,  571,
      571,  571,  572,    0,    0,  572,  573,    0,    0,  573,

      574,  574,    0,  574,  575,    0,    0,  575,  576,    0,
        0,  576,  578,    0,    0,  578,  579,  579,  579,  579,
      580,    0,    0,  580,  581,    0,    0,  581,  582,  582,
        0,  582,  583,    0,    0,  583,  584,    0,    0,  584,
      585,    0,    0,  585,  586,  586,  586,  586,  587,    0,
        0,  587,  588,  588,    0,  588,  589,    0,    0,  589,
      590,    0,    0,  590,  591,    0,    0,  591,  592,  592,
      592,  592,  593,    0,    0,  593,  594,  594,    0,  594,
      595,    0,    0,  595,  596,    0,    0,  596,  597,    0,
        0,  597,  598,  598,  598,  598,  599,    0,    0,  599,

      600,  600,    0,  600,  601,    0,    0,  601,  602,    0,
        0,  602,  603,    0,    0,  603,  604,  604,  604,  604,
      605,    0,    0,  605,  606,  606,    0,  606,  607,    0,
        0,  607,  608,    0,    0,  608,  609,    0,    0,  609,
      610,  610,  610,  610,  611,    0,    0,  611,  612,  612,
        0,  612,  613,    0,    0,  613,  614,    0,    0,  614,
      615,    0,    0,  615,  616,  616,  616,  616,  617,    0,
        0,  617,  618,  618,    0,  618,  619,    0,    0,  619,
      620,    0,    0,  620,  621,    0,    0,  621,  622,  622,
      622,  622,  623,    0,    0,  623,  624,  624,    0,  624,

      625,    0,    0,  625,  626,    0,    0,  626,  627,    0,
        0,  627,  628,  628,  628,  628,  629,    0,    0,  629,
      630,  630,    0,  630,  631,    0,    0,  631,  632,    0,
        0,  632,  633,    0,    0,  633,  634,  634,  634,  634,
      635,    0,    0,  635,  636,  636,    0,  636,  637,    0,
        0,  637,  638,    0,    0,  638,  639,    0,    0,  639,
      640,  640,  640,  640,  641,    0,    0,  641,  642,  642,
        0,  642,  643,    0,    0,  643,  644,    0,    0,  644,
      645,    0,    0,  645,  646,  646,  646,  646,  647,    0,
        0,  647,  648,  648,    0,  648,  649,    0,    0,  649,

      650,    0,    0,  650,  651,    0,    0,  651,  652,  652,
      652,  652,  653,    0,    0,  653,  654,  654,    0,  654,
      655,    0,    0,  655,  656,    0,    0,  656,  657,    0,
        0,  657,  658,  658,  658,  658,  659,    0,    0,  659,
      660,  660,    0,  660,  661,    0,    0,  661,  662,    0,
        0,  662,  663,    0,    0,  663,  664,  664,  664,  664,
      665,    0,    0,  665,  666,  666,    0,  666,  667,    0,
        0,  667,  668,    0,    0,  668,  669,    0,    0,  669,
      670,  670,  670,  670,  671,    0,    0,  671,  672,  672,
        0,  672,  673,    0,    0,  673,  674,    0,    0,  674,

      675,    0,    0,  675,  676,  676,  676,  676,  677,    0,
        0,  677,  678,  678,    0,  678,  679,    0,    0,  679,
      680,    0,    0,  680,  681,    0,    0,  681,  682,  682,
      682,  682,  683,    0,    0,  683,  684,  684,    0,  684,
      685,    0,    0,  685,  686,    0,    0,  686,  687,    0,
        0,  687,  688,  688,  688,  688,  689,    0,    0,  689,
      690,  690,    0,  690,  691,    0,    0,  691,  692,    0,
        0,  692,  693,    0,    0,  693,  694,  694,  694,  694,
      695,    0,    0,  695,  696,  696,    0,  696,  697,    0,
        0,  697,  698,    0,    0,  698,  699,    0,    0,  699,

      700,  700,  700,  700,  701,    0,    0,  701,  702,  702,
        0,  702,  703,    0,    0,  703,  704,    0,    0,  704,
      705,    0,    0,  705,  706,  706,  706,  706,  707,    0,
        0,  707,  708,  708,    0,  708,  709,    0,    0,  709,
      710,    0,    0,  710,  711,    0,    0,  711,  712,  712,
      712,  712,  713,    0,    0,  713,  714,  714,    0,  714,
      715,    0,    0,  715,  716,    0,    0,  716,  717,    0,
        0,  717,  718,  718,  718,  718,  719,    0,    0,  719,
      720,  720,    0,  720,  721,    0,    0,  721,  722,    0,
        0,  722,  723,    0,    0,  723,  724,  724,  724,  724,

      725,    0,    0,  725,  726,  726,    0,  726,  727,    0,
        0,  727,  728,    0,    0,  728,  729,    0,    0,  729,
      730,  730,  730,  730,  731,    0,    0,  731,  732,  732,
        0,  732,  733,    0,    0,  733,  734,    0,    0,  734,
      735,    0,    0,  735,  736,  736,  736,  736,  737,    0,
        0,  737,  738,  738,    0,  738,  739,    0,    0,  739,
      740,    0,    0,  740,  741,    0,    0,  741,  742,  742,
      742,  742,  743,    0,    0,  743,  744,  744,    0,  744,
      745,    0,    0,  745,  746,    0,    0,  746,  747,    0,
        0,  747,  748,  748,  748,  748,  749,    0,    0,  749,

      750,  750,    0,  750,  751,    0,    0,  751,  752,    0,
        0,  752,  753,    0,    0,  753,  754,  754,  754,  754,
      755,    0,    0,  755,  756,  756,    0,  756,  757,    0,
        0,  757,  758,    0,    0,  758,  759,    0,    0,  759,
      760,  760,  760,  760,  761,    0,    0,  761,  762,  762,
        0,  762,  763,    0,    0,  763,  764,    0,    0,  764,
      765,    0,    0,  765,  766,  766,  766,  766,  767,    0,
        0,  767,  768,  768,    0,  768,  769,    0,    0,  769,
      770,    0,    0,  770,  771,    0,    0,  771,  772,  772,
      772,  772,  773,    0,    0,  773,  774,  774,    0,  774,

      775,    0,    0,  775,  776,    0,    0,  776,  777,    0,
        0,  777,  778,  778,  778,  778,  779,    0,    0,  779,
      780,  780,    0,  780,  781,    0,    0,  781,  782,    0,
        0,  782,  783,    0,    0,  783,  784,  784,  784,  784,
      785,    0,    0,  785,  786,  786,    0,  786,  787,    0,
        0,  787,  788,    0,    0,  788,  789,    0,    0,  789,
      790,  790,  790,  790,  791,    0,    0,  791,  792,  792,
        0,  792,  793,    0,    0,  793,  794,    0,    0,  794,
      795,    0,    0,  795,  796,  796,  796,  796,  797,    0,
        0,  797,  798,  798,    0,  798,  799,    0,    0,  799,

      800,    0,    0,  800,  801,    0,    0,  801,  802,  802,
      802,  802,  803,    0,    0,  803,  804,  804,    0,  804,
      805,    0,    0,  805,  806,    0,    0,  806,  807,    0,
        0,  807,  808,  808,  808,  808,  809,    0,    0,  809,
      810,  810,    0,  810,  811,    0,    0,  811,  812,    0,
        0,  812,  813,    0,    0,  813,  814,  814,  814,  814,
      815,    0,    0,  815,  816,  816,    0,  816,  817,    0,
        0,  817,  818,    0,    0,  818,  819,    0,    0,  819,
      820,  820,  820,  820,  821,    0,    0,  821,  822,  822,
        0,  822,  823,    0,    0,  823,  824,    0,    0,  824,

      825,  825,  825,  825,  826,  826,    0,  826,  827,  827,
      827,  827,  828,  828,    0,  828,  829,  829,  829,  829,
      830,  830,    0,  830,  831,  831,  831,  831,  832,  832,
        0,  832,  833,  833,  833,  833,  834,  834,    0,  834,
      835,  835,    0,  835,  836,  836,    0,  836,  837,  837,
        0,  837,  838,  838,    0,  838,  839,  839,    0,  839,
      840,  840,    0,  840,  841,  841,    0,  841,  842,  842,
        0,  842,  843,  843,    0,  843,  844,  844,    0,  844,
      845,  845,    0,  845,  846,  846,    0,  846,  847,  847,
        0,  847,  848,  848,    0,  848,  849,  849,    0,  849,

      850,  850,    0,  850,  851,  851,    0,  851,  852,  852,
        0,  852,  853,  853,    0,  853,  854,  854,    0,  854,
      855,  855,    0,  855,  856,  856,    0,  856,  857,  857,
        0,  857,  858,  858,    0,  858,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507
    } ;

extern int clustal_flex_debug;
int clustal_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up clustaltext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *clustaltext;
#line 1 "clustall.l"
/* clustall.l - CLUSTAL alignment lexer */
#line 4 "clustall.l"
#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#ifdef STDC_HEADERS
# include <stdlib.h>
# include <string.h>
#endif

#include "align/clustaly.h"

#undef  YY_DECL
#define YY_DECL int clustallex(YYSTYPE *yylval)

#line 1245 "align/clustall.c"

#define INITIAL 0
#define HDRTAG 1
#define SEQTAG 2
#define CONTAG 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int clustallex_destroy (void );

int clustalget_debug (void );

void clustalset_debug (int debug_flag  );

YY_EXTRA_TYPE clustalget_extra (void );

void clustalset_extra (YY_EXTRA_TYPE user_defined  );

FILE *clustalget_in (void );

void clustalset_in  (FILE * _in_str  );

FILE *clustalget_out (void );

void clustalset_out  (FILE * _out_str  );

int clustalget_leng (void );

char *clustalget_text (void );

int clustalget_lineno (void );

void clustalset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int clustalwrap (void );
#else
extern int clustalwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( clustaltext, clustalleng, 1, clustalout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( clustalin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( clustalin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, clustalin))==0 && ferror(clustalin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(clustalin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int clustallex (void);

#define YY_DECL int clustallex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after clustaltext and clustalleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( clustalleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(clustaltext[clustalleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 44 "clustall.l"


#line 1438 "align/clustall.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)clustalalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in clustallex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! clustalin )
			clustalin = stdin;

		if ( ! clustalout )
			clustalout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			clustalensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				clustal_create_buffer(clustalin,YY_BUF_SIZE );
		}

		clustal_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of clustaltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 508 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 507 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 46 "clustall.l"
; /* Empty lines ignored */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 47 "clustall.l"
; /* Empty lines ignored */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "clustall.l"
; /* Empty lines at EOF ignored */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "clustall.l"
{ BEGIN HDRTAG; return TAG; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "clustall.l"
{ return TXT; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 52 "clustall.l"
{ BEGIN INITIAL; return EOL; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up clustaltext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up clustaltext again */
YY_RULE_SETUP
#line 53 "clustall.l"
{ BEGIN SEQTAG; return EOL; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 55 "clustall.l"
{ BEGIN SEQTAG; return EOL; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 56 "clustall.l"
/* Ignore masks lines */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "clustall.l"
{ yylval->str = strdup(clustaltext); return NAM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "clustall.l"
{ yylval->str = strdup(clustaltext); return BAS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "clustall.l"
{ return INT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "clustall.l"
{ return SPC; }
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up clustaltext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up clustaltext again */
YY_RULE_SETUP
#line 61 "clustall.l"
; /* Trailing spaces ignored */
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up clustaltext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up clustaltext again */
YY_RULE_SETUP
#line 62 "clustall.l"
{ return EOL; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up clustaltext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up clustaltext again */
YY_RULE_SETUP
#line 63 "clustall.l"
{ BEGIN CONTAG; return EOL; }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 64 "clustall.l"
{ BEGIN INITIAL; return EOL; }
	YY_BREAK
case YY_STATE_EOF(SEQTAG):
#line 65 "clustall.l"
{ BEGIN INITIAL; return EOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "clustall.l"
{ return ERR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "clustall.l"
{ return CON; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 69 "clustall.l"
{ BEGIN INITIAL; return EOL; }
	YY_BREAK
case YY_STATE_EOF(CONTAG):
#line 70 "clustall.l"
{ BEGIN INITIAL; return EOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "clustall.l"
{ return ERR; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HDRTAG):
#line 73 "clustall.l"
{ return END; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 74 "clustall.l"
{ return ERR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "clustall.l"
{ return ERR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "clustall.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1708 "align/clustall.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed clustalin at a new source and called
			 * clustallex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = clustalin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( clustalwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * clustaltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of clustallex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			clustalrestart(clustalin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) clustalrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 508 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 508 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 507);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					clustalrestart(clustalin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( clustalwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve clustaltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void clustalrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        clustalensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            clustal_create_buffer(clustalin,YY_BUF_SIZE );
	}

	clustal_init_buffer(YY_CURRENT_BUFFER,input_file );
	clustal_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void clustal_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		clustalpop_buffer_state();
	 *		clustalpush_buffer_state(new_buffer);
     */
	clustalensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	clustal_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (clustalwrap()) processing, but the only time this flag
	 * is looked at is after clustalwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void clustal_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	clustalin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE clustal_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) clustalalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in clustal_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) clustalalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in clustal_create_buffer()" );

	b->yy_is_our_buffer = 1;

	clustal_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with clustal_create_buffer()
 * 
 */
    void clustal_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		clustalfree((void *) b->yy_ch_buf  );

	clustalfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a clustalrestart() or at EOF.
 */
    static void clustal_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	clustal_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then clustal_init_buffer was _probably_
     * called from clustalrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void clustal_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		clustal_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void clustalpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	clustalensure_buffer_stack();

	/* This block is copied from clustal_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from clustal_switch_to_buffer. */
	clustal_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void clustalpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	clustal_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		clustal_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void clustalensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)clustalalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clustalensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)clustalrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clustalensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE clustal_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) clustalalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in clustal_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	clustal_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to clustallex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       clustal_scan_bytes() instead.
 */
YY_BUFFER_STATE clustal_scan_string (yyconst char * yystr )
{
    
	return clustal_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to clustallex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE clustal_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) clustalalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in clustal_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = clustal_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in clustal_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up clustaltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		clustaltext[clustalleng] = (yy_hold_char); \
		(yy_c_buf_p) = clustaltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		clustalleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int clustalget_lineno  (void)
{
        
    return clustallineno;
}

/** Get the input stream.
 * 
 */
FILE *clustalget_in  (void)
{
        return clustalin;
}

/** Get the output stream.
 * 
 */
FILE *clustalget_out  (void)
{
        return clustalout;
}

/** Get the length of the current token.
 * 
 */
int clustalget_leng  (void)
{
        return clustalleng;
}

/** Get the current token.
 * 
 */

char *clustalget_text  (void)
{
        return clustaltext;
}

/** Set the current line number.
 * @param _line_number
 * 
 */
void clustalset_lineno (int  _line_number )
{
    
    clustallineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see clustal_switch_to_buffer
 */
void clustalset_in (FILE *  _in_str )
{
        clustalin = _in_str ;
}

void clustalset_out (FILE *  _out_str )
{
        clustalout = _out_str ;
}

int clustalget_debug  (void)
{
        return clustal_flex_debug;
}

void clustalset_debug (int  _bdebug )
{
        clustal_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from clustallex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    clustalin = stdin;
    clustalout = stdout;
#else
    clustalin = (FILE *) 0;
    clustalout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * clustallex_init()
     */
    return 0;
}

/* clustallex_destroy is for both reentrant and non-reentrant scanners. */
int clustallex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		clustal_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		clustalpop_buffer_state();
	}

	/* Destroy the stack itself. */
	clustalfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    clustalfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * clustallex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *clustalalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *clustalrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void clustalfree (void * ptr )
{
	free( (char *) ptr );	/* see clustalrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 77 "clustall.l"



